#version 450
//#extension GL_ARB_separate_shader_objects : enable

layout(local_size_x_id = 1) in;
layout(local_size_y_id = 2) in;
layout(local_size_z_id = 3) in;
layout(constant_id = 4) const uint testVal = 2;

void main() {
    //outColor = subpassLoad(inputColor);
//    ivec2 coord = ivec2(gl_GlobalInvocationID.x, gl_GlobalInvocationID.y);
//    vec4 color = imageLoad(inputColor, coord);
//    imageStore(outputColor, coord, color);
    //outColor = vec4(0.5, 0.2, 0.8, 1.0);
}